import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-950`}
      >
        <nav className="w-full bg-blue-700 dark:bg-blue-900 shadow mb-8">
          <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
            <Link
              href="/sessions"
              className="text-white font-bold text-xl tracking-wide hover:text-blue-200"
            >
              IE Crash Course Diary
            </Link>
            <div className="space-x-4">
              <Link
                href="/"
                className="text-white hover:text-blue-200 font-medium flex items-center gap-2"
                aria-label="Home"
              >
                <svg
                  aria-label="Home"
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3 12l9-9 9 9M4 10v10a1 1 0 001 1h5m6-11v11a1 1 0 01-1 1h-5"
                  />
                </svg>
              </Link>
            </div>
          </div>
        </nav>
        <main className="min-h-[80vh]">{children}</main>
      </body>
      <footer className="w-full bg-gray-200 dark:bg-gray-800 py-4 mt-8">
        <div className="max-w-4xl mx-auto text-center text-gray-600 dark:text-gray-400">
          <p className="mb-2">
            Learn more about the{" "}
            <a
              href="https://isha.sadhguru.org/us/en/inner-engineering"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-700 dark:text-blue-400 underline hover:text-blue-900 dark:hover:text-blue-200"
            >
              Inner Engineering program
            </a>
          </p>
          <p className="text-sm">
            &copy; {new Date().getFullYear()} Praneeth Yerrapragada
          </p>
        </div>
      </footer>
    </html>
  );
}
